### PR TITLE
Created the Semaphore config and added a Rubocop block

### PR DESCRIPTION
**Pull request by vivek-viswam-rv**
Part of: https://github.com/bigbinary/neeto-engineering-web/issues/277

@yedhink _a Please review the changes.

### CODE REVIEW

**Comment by sandip-mane** [comment]
@vivek-viswam-rv same is already done here: https://github.com/bigbinary/neeto-monitor-ruby/pull/23/files

**Comment by vivek-viswam-rv** [comment]
@sandip-mane 
Oh, okay. I've a doubt, aren't we supposed to add `rubocop` gem to the `test` group also, in the `Gemfile`? Didn't see it in that commit.
https://github.com/bigbinary/neeto-monitor-ruby/blob/88a41549f9f5c36f5375b482ae5da1213aa1eb3c/Gemfile#L8-L21

**Comment by sandip-mane** [comment]
@vivek-viswam-rv yes, it needs to be added to the test too in order for the check to work in semaphoreci.

**Comment by vivek-viswam-rv** [comment]
@sandip-mane I'll close this PR and create a separate issue to add the `rubocop` dependency in the `test` group then.
Thanks for letting me know.

**Comment by sandip-mane** [comment]
@vivek-viswam-rv please check for consistency, add it only if it's needed and other projects are adding it too. 

As per [this file](https://github.com/bigbinary/neeto-commons-backend/blob/d15247e6e49d7d8f15dc1a1f1e6d920e6209bf44/lib/neeto_commons_backend/gemfiles/Gemfile.common.rb), it probably does not need to be added to **test group**.

**Comment by vivek-viswam-rv** [comment]
@sandip-mane Actually, the `rubocop` dependency is mentioned without any groups in the [Gemfile](https://github.com/bigbinary/neeto-commons-backend/blob/7c14ec78e588d1b93b1b3caa909aad179bdd8396/Gemfile#L30) in the root directory of that repository. 

Also, there's no actual benefit of adding dependencies under any group, if we are simply executing `bundle install`.
`bundle install` **installs all the gems under every group in this case**.

But we could exclude groups by passing the option `--without <group_name>` to the bundle install.

As per my understanding, we have been using groups incorrectly. We are not gaining any benefit from grouping since we are not passing any options.

See [this](https://github.com/bigbinary/neeto-monitor-ruby/blob/88a41549f9f5c36f5375b482ae5da1213aa1eb3c/.semaphore/semaphore.yml#L14) semaphore config. Here we are executing the `bundle install` without passing the exclusion option.

This issue is not limited to this repo, I believe it's the case in every repo.

Please correct me if I'm wrong.

@yedhink Should we do something about this?

**Comment by sandip-mane** [comment]
@vivek-viswam-rv 

> the rubocop dependency is mentioned without any groups in the [Gemfile](https://github.com/bigbinary/neeto-commons-backend/blob/7c14ec78e588d1b93b1b3caa909aad179bdd8396/Gemfile#L30) in the root directory of that repository.

This Gemfile is for the `neeto-commons-backend` engine, which is not used for standardizing other neetoProducts.

> See [this](https://github.com/bigbinary/neeto-monitor-ruby/blob/88a41549f9f5c36f5375b482ae5da1213aa1eb3c/.semaphore/semaphore.yml#L14) semaphore config. Here we are executing the bundle install without passing the exclusion option.

This works with ENV, ie. refer: https://github.com/bigbinary/neeto-monitor-ruby/blob/88a41549f9f5c36f5375b482ae5da1213aa1eb3c/.semaphore/semaphore.yml#L19-L22

**Comment by sandip-mane** [comment]
Yeah, even `RAILS_ENV=production bundle install` installs the `spring` gem. Seems like it's not working.

**Comment by vivek-viswam-rv** [comment]
@sandip-mane As far as I understand, the correct way to execute is by running `bundle install --without development` in Semaphore.
And the environment variables such as `RAILS_ENV` don't have an effect on group selection, as `bundle` is independent of the Rails.

Like I had previous metioned in the comment https://github.com/bigbinary/neeto-monitor-ruby/pull/22#issuecomment-1430985350, we are not using the `bundle install` correctly in our products.

@yedhink Shouldn't we do something about this? Also, this issue is not documented in the LRRB.

**Comment by sandip-mane** [comment]
@vivek-viswam-rv 

> bundle is independent of the Rails.

It's not totally independent as we inform which group it should take here: 
https://github.com/bigbinary/neeto-kb-web/blob/4ec6e727a01de3d3a743f8b76868d025183d62d8/config/application.rb#L5

**Comment by yedhink** [comment]
@vivek-viswam-rv Good observation. I think we should be passing the `--without` flag in Semaphore to ignore all `development` gems and just stick onto the default and test gems.

Another thing is that bundler caches the value that we pass to `--without` in the `.bundle/config` if we set it to config, such that next time we simply do `bundle install`, it automatically uses the previous `without` value. Hopefully this config is not added to git tree.

>https://github.com/bigbinary/neeto-kb-web/blob/4ec6e727a01de3d3a743f8b76868d025183d62d8/config/application.rb#L5

With that being said, if we have this config that loads all groups during load time, then I think we'd have to pass the ENV variable `BUNDLE_WITHOUT="development"` when invoking `bundle install` to make things work, as per their docs.

----

@sandip-mane What are your thoughts on taking this up as a standardization issue?

References:
- https://bundler.io/guides/groups.html
- https://bundler.io/guides/bundler_setup.html

**Comment by vivek-viswam-rv** [comment]
@yedhink 
> Hopefully this config is not added to git tree

I had verified that, it won't be added to git tree. Both [neeto-wheel-web](https://github.com/bigbinary/neeto-wheel-web/blob/06f8275459d173dddc5d2f06974e5fa227a65048/.gitignore#L2) and [wheel](https://github.com/bigbinary/wheel/blob/192e9469be6a1ae58c76c66f024537091b8ab920/.gitignore#L2) ignores the `.bundle` directory.

**Comment by sandip-mane** [comment]
I looked a bit deeper, and it is working as it should work in Rails. `bundle install` installs all gems and Rails loads gems based on the group. 

We can improve it further on semaphore by specifying the group. (It could result in a somewhat faster build time).

@yedhink if that is worth it, we could take it up.

**Comment by yedhink** [comment]
>We can improve it further on semaphore by specifying the group. (It could result in a somewhat faster build time).

Let's actually do it. I think in the longer run it might benefit us.

**Pull request closed without merging**
